name: CI

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
  workflow_dispatch:

# Cancel in-progress runs when starting a new one.
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  # Verify code format and build integrity for every PR.
  build-integrity:
    name: Build Integrity
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:

      - name: Checkout code
        id: checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref || github.ref_name }}
          token: ${{ secrets.GITHUB_TOKEN }}
